site_name: Techtonic 22 - Docker
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
  palette:
    scheme: slate
    primary: orange
    accent: deep orange
  icon:
    repo: fontawesome/brands/github
  features:
    - instant
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - tabs
nav:
  - Workshop:
      - index.md
      - What is Docker?: 1.1-what-is-docker.md
      - Images & Containers: 1.2-images-containers.md
      - Virtual Machines: 1.3-vms.md
      - Persistence: 1.4-persistence.md
      - Clone: 1.5-clone.md
      - Build: 1.6-build.md
      - Change Code: 1.7-change-code.md
      - Stop Container: 1.8-stop-container.md
      - Build Again: 1.9-build-again.md
      - Multi Container: 1.10-multi-container.md
      - Container 2 Container: 1.11-container-2-container.md
      - Hot reloading within Docker: 1.12-local-dev.md
      - Clean up: 1.13-clean-up.md