site_name: Techtonic 22 - Docker
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  palette:
    scheme: slate
    primary: yellow
    accent: yellow
  icon:
    repo: fontawesome/brands/github
  features:
    - instant
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - search.highlight
    - tabs
nav:
  - Workshop:
      - index.md
      - What is Docker?: 1.01-what-is-docker.md
      - Images & Containers: 1.02-images-containers.md
      - Virtual Machines: 1.03-vms.md
      - Persistence: 1.04-persistence.md
      - Clone: 1.05-clone.md
      - Build: 1.06-build.md
      - Change Code: 1.07-change-code.md
      - Stop Container: 1.08-stop-container.md
      - Build Again: 1.09-build-again.md
      - Multi Container: 1.10-multi-container.md
      - Container 2 Container: 1.11-container-2-container.md
      - Hot reloading within Docker: 1.12-local-dev.md
      - Clean up: 1.13-clean-up.md
      - Recap: 1.14-recap.md
extra_css:
  - stylesheets/vgw.css